const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "../.env"), quiet: true });
const { verifyEmailConnection } = require("../src/config/email");

verifyEmailConnection().then(() => {
  console.log("Email server connection and authentication succeeded. No email was sent.");
}).catch(error => {
  if (error.code === "EAUTH") {
    console.error("Gmail rejected the sender credentials. Set SMTP_USER to the sender address and SMTP_PASS to a Google App Password generated by that same account, then restart the backend.");
  } else {
    console.error("Email connection failed (%s). Check the SMTP settings and network connection.", error.code || "configuration error");
  }
  process.exitCode = 1;
});
